name: 'Tests: E2E'

on:
  deployment_status:

env:
  DOPPLER_TOKEN: ${{ secrets.DOPPLER_TOKEN }}

jobs:
  playwright:
    name: Playwright
    if: github.event.deployment_status.state == 'success'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Doppler CLI
        uses: DopplerHQ/cli-action@v2

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Install Playwright dependencies
        run: pnpm exec playwright install --with-deps

      - name: Run code generation
        run: pnpm run codegen

      - name: Run tests
        run: pnpm run test
        env:
          PLAYWRIGHT_TEST_BASE_URL: ${{ github.event.deployment_status.environment_url }}
