targets:
  $default:
    builders:
      ferry_generator|graphql_builder:
        enabled: true
        options:
          schema: glyph|lib/graphql/schema.graphql
          when_extensions:
            when: true
            maybeWhen: true
          type_overrides:
            JSON:
              name: JsonObject
              import: "package:built_value/json_object.dart"
      ferry_generator|serializer_builder:
        enabled: true
        options:
          schema: glyph|lib/graphql/schema.graphql
          type_overrides:
            JSON:
              name: JsonObject
              import: "package:built_value/json_object.dart"
          custom_serializers:
            - import: "package:built_value/src/json_object_serializer.dart"
              name: JsonObjectSerializer
