name: glyph
description: Glyph mobile app
publish_to: none
version: 1.0.0

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  assorted_layout_widgets: ^9.0.2
  auto_route: '^8.1.3'
  built_value: ^8.9.2
  cached_network_image: ^3.3.1
  card_swiper: '^3.0.1'
  collection: '^1.18.0'
  custom_refresh_indicator: '^3.1.0'
  datadog_flutter_plugin: ^2.6.0
  external_app_launcher: '^4.0.0'
  ferry: '^0.16.0+1'
  ferry_flutter: '^0.9.0-dev.3'
  firebase_analytics: ^11.1.0
  firebase_core: '^3.0.0'
  firebase_messaging: '^15.0.0'
  flutter:
    sdk: flutter
  flutter_form_builder: '^9.3.0'
  flutter_inappwebview: '^6.0.0'
  flutter_native_splash: '^2.4.0'
  flutter_naver_login: '^1.8.0'
  flutter_randomcolor: ^1.0.15
  flutter_riverpod: '^2.5.1'
  flutter_secure_storage: '^9.2.1'
  flutter_svg: '^2.0.10+1'
  fluttertoast: '^8.2.5'
  form_builder_validators: ^11.0.0
  freezed_annotation: '^2.4.1'
  gap: '^3.0.1'
  get_it: '^7.7.0'
  google_sign_in: '^6.2.1'
  gql_exec: '^1.0.0+1'
  gql_http_link: '^1.0.1+1'
  gql_link: '^1.0.0+1'
  http: ^1.2.1
  iamport_flutter: ^0.10.19
  image_picker: '^1.1.2'
  in_app_purchase: '^3.2.0'
  intl: ^0.19.0
  jiffy: '^6.3.1'
  json_annotation: ^4.9.0
  mixpanel_flutter: '^2.2.0'
  nested_scroll_view_plus: ^2.0.0
  package_info_plus: '^8.0.0'
  permission_handler: '^11.3.1'
  pinput: '^5.0.0'
  riverpod_annotation: '^2.3.5'
  sentry_flutter: ^8.3.0
  share_plus: '^9.0.0'
  shared_preferences: ^2.2.3
  sign_in_with_apple: '^6.1.0'
  sliver_tools: '^0.2.12'
  transparent_image: '^2.0.1'
  url_launcher: '^6.3.0'
  uuid: ^4.4.0

dev_dependencies:
  auto_route_generator: '^8.0.0'
  build_runner: '^2.4.10'
  custom_lint: '^0.6.4'
  ferry_generator: '^0.10.0'
  flutter_lints: '^4.0.0'
  flutter_test:
    sdk: flutter
  freezed: '^2.5.2'
  json_serializable: ^6.8.0
  riverpod_generator: '^2.4.0'
  riverpod_lint: '^2.3.10'

flutter:
  uses-material-design: true

  assets:
    - assets/emojis/
    - assets/icons/
    - assets/logos/
    - assets/prosemirror_widgets/

  fonts:
    - family: SUIT
      fonts:
        - asset: assets/fonts/SUIT-Thin.woff2
          weight: 100
        - asset: assets/fonts/SUIT-ExtraLight.woff2
          weight: 200
        - asset: assets/fonts/SUIT-Light.woff2
          weight: 300
        - asset: assets/fonts/SUIT-Regular.woff2
          weight: 400
        - asset: assets/fonts/SUIT-Medium.woff2
          weight: 500
        - asset: assets/fonts/SUIT-SemiBold.woff2
          weight: 600
        - asset: assets/fonts/SUIT-Bold.woff2
          weight: 700
        - asset: assets/fonts/SUIT-ExtraBold.woff2
          weight: 800
        - asset: assets/fonts/SUIT-Heavy.woff2
          weight: 900
    - family: Pretendard
      fonts:
        - asset: assets/fonts/Pretendard-Thin.woff2
          weight: 100
        - asset: assets/fonts/Pretendard-ExtraLight.woff2
          weight: 200
        - asset: assets/fonts/Pretendard-Light.woff2
          weight: 300
        - asset: assets/fonts/Pretendard-Regular.woff2
          weight: 400
        - asset: assets/fonts/Pretendard-Medium.woff2
          weight: 500
        - asset: assets/fonts/Pretendard-SemiBold.woff2
          weight: 600
        - asset: assets/fonts/Pretendard-Bold.woff2
          weight: 700
        - asset: assets/fonts/Pretendard-ExtraBold.woff2
          weight: 800
        - asset: assets/fonts/Pretendard-Black.woff2
          weight: 900
    - family: KoPubWorldBatang
      fonts:
        - asset: assets/fonts/KoPubWorldBatangMedium.woff2
          weight: 400
        - asset: assets/fonts/KoPubWorldBatangBold.woff2
          weight: 700
    - family: KoPubWorldDotum
      fonts:
        - asset: assets/fonts/KoPubWorldDotumMedium.woff2
          weight: 400
        - asset: assets/fonts/KoPubWorldDotumBold.woff2
          weight: 700
    - family: NanumBarunGothic
      fonts:
        - asset: assets/fonts/NanumBarunGothic.woff2
          weight: 400
        - asset: assets/fonts/NanumBarunGothicBold.woff2
          weight: 700
    - family: NanumMyeongjo
      fonts:
        - asset: assets/fonts/NanumMyeongjo.woff2
          weight: 400
        - asset: assets/fonts/NanumMyeongjoBold.woff2
          weight: 700
    - family: RIDIBatang
      fonts:
        - asset: assets/fonts/RIDIBatang.woff2
          weight: 400
    - family: TablerIcons
      fonts:
        - asset: assets/fonts/TablerIcons.ttf
    - family: TablerBoldIcons
      fonts:
        - asset: assets/fonts/TablerBoldIcons.ttf
    - family: GlyphIcons
      fonts:
        - asset: assets/fonts/GlyphIcons.ttf
