name: glyph
description: Glyph mobile app
publish_to: none
version: 1.0.0

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  animate_do: '^3.3.4'
  assorted_layout_widgets: ^9.0.2
  auto_route: '^8.1.3'
  built_value: ^8.9.2
  cached_network_image: ^3.3.1
  card_swiper: '^3.0.1'
  collection: '^1.18.0'
  custom_refresh_indicator: '^3.1.0'
  dartx: '^1.2.0'
  envied: '^0.5.4+1'
  external_app_launcher: '^4.0.0'
  ferry: '^0.16.0+1'
  ferry_flutter: '^0.9.0-dev.3'
  firebase_core: '^3.0.0'
  firebase_messaging: '^15.0.0'
  flutter:
    sdk: flutter
  flutter_form_builder: '^9.3.0'
  flutter_inappwebview: '^6.0.0'
  flutter_native_splash: '^2.4.0'
  flutter_naver_login: '^1.8.0'
  flutter_randomcolor: ^1.0.15
  flutter_riverpod: '^2.5.1'
  flutter_secure_storage: '^9.2.1'
  flutter_svg: '^2.0.10+1'
  fluttertoast: '^8.2.5'
  form_builder_validators: '^10.0.1'
  freezed_annotation: '^2.4.1'
  gap: '^3.0.1'
  get_it: '^7.7.0'
  google_sign_in: '^6.2.1'
  gql_exec: '^1.0.0+1'
  gql_http_link: '^1.0.1+1'
  gql_link: '^1.0.0+1'
  http: ^1.2.1
  iamport_flutter: ^0.10.19
  image_picker: '^1.1.2'
  in_app_purchase: '^3.2.0'
  intl: ^0.19.0
  jiffy: '^6.3.1'
  mixpanel_flutter: '^2.2.0'
  nested_scroll_view_plus: ^2.0.0
  package_info_plus: '^8.0.0'
  permission_handler: '^11.3.1'
  pinput: '^5.0.0'
  riverpod_annotation: '^2.3.5'
  share_plus: '^9.0.0'
  shared_preferences: ^2.2.3
  sign_in_with_apple: '^6.1.0'
  sliver_tools: '^0.2.12'
  transparent_image: '^2.0.1'
  url_launcher: '^6.3.0'
  uuid: ^4.4.0

dev_dependencies:
  auto_route_generator: '^8.0.0'
  build_runner: '^2.4.10'
  custom_lint: '^0.6.4'
  envied_generator: '^0.5.4+1'
  ferry_generator: '^0.10.0'
  flutter_launcher_icons: ^0.13.1
  flutter_lints: '^4.0.0'
  flutter_test:
    sdk: flutter
  freezed: '^2.5.2'
  riverpod_generator: '^2.4.0'
  riverpod_lint: '^2.3.10'

flutter:
  uses-material-design: true

  assets:
    - assets/emojis/
    - assets/images/
    - assets/icons/
    - assets/logos/

  fonts:
    - family: SUIT
      fonts:
        - asset: assets/fonts/SUIT-Thin.ttf
          weight: 100
        - asset: assets/fonts/SUIT-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/SUIT-Light.ttf
          weight: 300
        - asset: assets/fonts/SUIT-Regular.ttf
          weight: 400
        - asset: assets/fonts/SUIT-Medium.ttf
          weight: 500
        - asset: assets/fonts/SUIT-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/SUIT-Bold.ttf
          weight: 700
        - asset: assets/fonts/SUIT-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/SUIT-Heavy.ttf
          weight: 900
    - family: TablerIcons
      fonts:
        - asset: assets/fonts/TablerIcons.ttf
    - family: TablerBoldIcons
      fonts:
        - asset: assets/fonts/TablerBoldIcons.ttf
    - family: GlyphIcons
      fonts:
        - asset: assets/fonts/GlyphIcons.ttf

flutter_launcher_icons:
  image_path: assets/images/icon.png

  android: true
  adaptive_icon_background: '#171717'
  adaptive_icon_foreground: assets/images/adaptive_icon_foreground.png

  ios: true

flutter_native_splash:
  color: '#171717'
  image: assets/images/splash.png

  android_12:
    color: '#171717'
