name: CD (Preview)

on:
  pull_request:
    types: [opened, synchronize]

env:
  TURBO_TEAM: penxle
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}

jobs:
  deploy:
    name: ${{ matrix.project }}
    runs-on: ubuntu-latest
    container: node:18-alpine
    strategy:
      fail-fast: false
      matrix:
        project:
          - penxle.com
          - penxle.io
          - help.penxle.com
          - landing.penxle.com
    concurrency:
      group: ${{ matrix.project }}-pr-${{ github.event.pull_request.number }}
      cancel-in-progress: true
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        # with:
        #   ref: ${{ github.event.inputs.ref }}

      - name: Setup Pulumi
        uses: pulumi/actions@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Prepare local actions
        run: pnpm run build:actions

      - name: Build local dependencies
        run: pnpm run build:deps

      - name: Fetch secrets
        uses: dopplerhq/secrets-fetch-action@v1.1.2
        with:
          doppler-token: ${{ secrets.DOPPLER_TOKEN }}
          doppler-project: penxle-com
          doppler-config: preview
          inject-env-vars: true

      - name: Build project
        run: pnpm exec turbo run build --filter=${{ matrix.project }}

      - name: Upload lambda function
        uses: ./actions/upload-lambda
        with:
          project: ${{ matrix.project }}
          stack: pr-${{ github.event.pull_request.number }}
        env:
          AWS_REGION: ap-northeast-2
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Deploy infrastructure
        run: |
          cd infra/${{ matrix.project }}
          pulumi stack select penxle/pr-${{ github.event.pull_request.number }} || pulumi stack init penxle/pr-${{ github.event.pull_request.number }}
          pulumi config set aws:defaultTags '{"tags":{"ManagedBy":"Pulumi"}}'
          pulumi up --skip-preview --stack penxle/pr-${{ github.event.pull_request.number }}
        env:
          AWS_REGION: ap-northeast-2
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
