name: CD (Production)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: ${{ matrix.app }}
    runs-on: ubuntu-latest
    container: amazonlinux:2
    strategy:
      fail-fast: false
      matrix:
        app:
          - github-app
          - literoom
          - penxle.com
          - penxle.io
          - help.penxle.com
          - landing.penxle.com
    concurrency:
      group: production/${{ matrix.app }}
    steps:
      - name: Install binaries
        run: |
          yum install -y git tar zstd

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: pnpm

      - name: Setup doppler
        uses: dopplerhq/cli-action@v2

      - name: Setup pulumi
        uses: pulumi/actions@v4

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Setup doppler project
        run: doppler setup --no-interactive
        env:
          DOPPLER_TOKEN: ${{ secrets.DOPPLER_TOKEN }}
          DOPPLER_CONFIG: prod

      - name: Build app
        run: doppler run -- pnpm exec turbo run build
        working-directory: apps/${{ matrix.app }}
        env:
          TURBO_TEAM: penxle
          TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
          DOPPLER_TOKEN: ${{ secrets.DOPPLER_TOKEN }}
          PUBLIC_PULUMI_STACK: production

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Upload lambda function
        uses: ./packages/lambda
        with:
          app: ${{ matrix.app }}
          stack: production

      - name: Deploy infrastructure
        working-directory: apps/${{ matrix.app }}
        run: |
          pulumi stack select $STACK || pulumi stack init $STACK
          pulumi config set aws:defaultTags '{"tags":{"ManagedBy":"Pulumi"}}'
          pulumi up --skip-preview --stack $STACK
        env:
          STACK: penxle/production
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
