name: CD (Production)

on:
  push:
    branches:
      - main

jobs:
  preview:
    name: ${{ matrix.project }}
    runs-on: ubuntu-latest
    container: amazonlinux:2
    strategy:
      fail-fast: false
      matrix:
        project: [penxle.com, penxle.io, help.penxle.com, landing.penxle.com]
    concurrency:
      group: ${{ matrix.project }}
      cancel-in-progress: true
    steps:
      - name: Install binaries
        run: |
          yum install -y git tar zstd

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: pnpm

      - name: Setup doppler
        uses: dopplerhq/cli-action@v2

      - name: Setup Pulumi
        uses: pulumi/actions@v4

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build project
        run: DOPPLER_PROJECT=${DOPPLER_PROJECT/\./-} doppler run -- pnpm exec turbo run build --filter=${{ matrix.project }}
        env:
          TURBO_TEAM: penxle
          TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
          DOPPLER_TOKEN: ${{ secrets.DOPPLER_TOKEN }}
          DOPPLER_PROJECT: ${{ matrix.project }}
          DOPPLER_CONFIG: prod

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Upload lambda function
        id: upload-lambda
        uses: ./packages/lambda
        with:
          project: ${{ matrix.project }}
          stack: production

      - name: Deploy infrastructure
        run: |
          cd ${{ steps.upload-lambda.outputs.project-dir }}
          pulumi stack select $STACK || pulumi stack init $STACK
          pulumi config set aws:defaultTags '{"tags":{"ManagedBy":"Pulumi"}}'
          pulumi up --skip-preview --stack $STACK
        env:
          STACK: penxle/production
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
