name: cd/test

on:
  pull_request:
    types: [synchronize]

env:
  TURBO_TEAM: penxle
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        project: [penxle.com, penxle.io, help.penxle.com, landing.penxle.com]
    outputs:
      status: ${{ steps.changes.outputs.status }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Check changes
        id: changes
        run: |
          echo "status=proceed2" >> "$GITHUB_OUTPUT"

  test2:
    name: Test 2
    runs-on: ubuntu-latest
    needs: test
    if: ${{ needs.test.outputs.status == 'proceed' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
