name: cd/temp

on:
  pull_request:
    types: [synchronize]

env:
  TURBO_TEAM: penxle
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    container: amazonlinux:2
    concurrency: github-app
    steps:
      - name: Install binaries
        run: |
          yum install -y git tar zstd

      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Setup Pulumi
        uses: pulumi/actions@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Prepare local actions
        run: pnpm run build:actions

      - name: Build local dependencies
        run: pnpm run build:deps

      - name: Fetch secrets
        uses: dopplerhq/secrets-fetch-action@v1.1.2
        with:
          doppler-token: ${{ secrets.DOPPLER_TOKEN }}
          doppler-project: penxle-com
          doppler-config: prod
          inject-env-vars: true

      - name: Build project
        run: pnpm exec turbo run build --filter=github-app

      - name: Upload lambda function
        uses: ./actions/upload-lambda
        with:
          stack: production
          project: github-app
        env:
          AWS_REGION: ap-northeast-2
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Deploy infrastructure
        run: |
          cd infra/github-app
          pulumi stack select penxle/production || pulumi stack init penxle/production
          pulumi config set aws:defaultTags '{"tags":{"ManagedBy":"Pulumi"}}'
          pulumi up --skip-preview --stack penxle/production
        env:
          AWS_REGION: ap-northeast-2
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
