name: CD (Test 2)

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  deploy:
    name: ${{ matrix.project }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        project:
          - penxle.com
          - penxle.io
          - help.penxle.com
          - landing.penxle.com
    concurrency:
      group: ${{ matrix.project }}-pr-${{ github.event.pull_request.number }}
      cancel-in-progress: true
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
        with:
          mask-password: true

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ${{ env.ECR_REGISTRY }}/test
          tags: |
            type=raw,value=${{ matrix.project }}-pr-${{ github.event.pull_request.number }}
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          push: true
          provenance: false
          build-args: |
            PROJECT_NAME=${{ matrix.project }}
            PROJECT_PATH=sites/${{ matrix.project }}
            TURBO_TEAM=penxle
            TURBO_TOKEN=${{ secrets.TURBO_TOKEN }}
            DOPPLER_TOKEN=${{ secrets.DOPPLER_TOKEN }}
            DOPPLER_PROJECT=penxle-com
            DOPPLER_CONFIG=preview
          cache-from: type=gha
          cache-to: type=gha,mode=max
