name: CD

on:
  workflow_dispatch:
    inputs:
      project:
        required: true
        type: string
      stack:
        required: true
        type: string
      path:
        required: true
        type: string
      doppler-project:
        required: true
        type: string
      doppler-config:
        required: true
        type: string

jobs:
  deploy:
    name: ${{ github.event.inputs.stack }}/${{ github.event.inputs.project }}
    runs-on: ubuntu-latest
    container: amazonlinux:2
    concurrency:
      group: ${{ github.event.inputs.stack }}/${{ github.event.inputs.project }}
    steps:
      - name: Install binaries
        run: |
          yum install -y git tar zstd

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: pnpm

      - name: Setup doppler
        uses: dopplerhq/cli-action@v2

      - name: Setup Pulumi
        uses: pulumi/actions@v4

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build project
        run: doppler run -- pnpm exec turbo run build --filter=${{ github.event.inputs.project }}
        shell: bash
        env:
          TURBO_TEAM: penxle
          TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
          DOPPLER_TOKEN: ${{ secrets.DOPPLER_TOKEN }}
          DOPPLER_PROJECT: ${{ github.event.inputs.doppler-project }}
          DOPPLER_CONFIG: ${{ github.event.inputs.doppler-config }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Upload lambda function
        uses: ./packages/lambda
        with:
          project: ${{ github.event.inputs.project }}
          stack: ${{ github.event.inputs.stack }}

      - name: Deploy infrastructure
        run: |
          cd ${{ github.event.inputs.path }}
          pulumi stack select $STACK || pulumi stack init $STACK
          pulumi config set aws:defaultTags '{"tags":{"ManagedBy":"Pulumi"}}'
          pulumi up --skip-preview --stack $STACK
        env:
          STACK: penxle/${{ github.event.inputs.stack }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
